Added path-finders for the posix tools: cmake, dig, git.cmd, hg, and nmap.

diff --git a/posix/bin/dig b/posix/bin/dig
--- a/posix/bin/dig
+++ b/posix/bin/dig
@@ -1,3 +1,23 @@
 #!/bin/sh
-dig="$HOME/tools/bind-tools/dig.exe"
-"$dig" "$@"
+posix=dig
+windows=`resolvepath "$HOME/tools/bind-tools"`/dig.exe
+
+## Figure out the right path to run
+case "$platform" in
+    msys|cygwin)
+        prog=`[ -x "$windows" ] && echo "$windows"`
+        ;;
+esac
+
+if [ -z "$prog" ]; then
+    argv0=`readlink -f "$0"`
+    IFS=:
+    for p in $PATH; do
+        rp=`readlink -f "$p/$posix"`
+        [ -x "$rp" ] && [ `stat -f%i "$argv0" 2>/dev/null || echo "$argv0"` != `stat -f%i "$rp" 2>/dev/null || echo "$rp"` ] && prog="$rp"
+    done
+fi
+
+[ -z "$prog" ] && echo "Unable to locate $posix" 1>&2 && exit 1
+"$prog" "$@"
+exit $
diff --git a/posix/bin/hg b/posix/bin/hg
--- a/posix/bin/hg
+++ b/posix/bin/hg
@@ -1,3 +1,25 @@
 #!/bin/sh
-path="/c/Python/Scripts"
-"$path/hg" "$@"
+posix=hg
+windows="$PythonPath/Scripts/hg.exe"
+
+## determine which program to run
+case "$platform" in
+    msys|cygwin)
+        prog=`[ -x "$windows" ] && echo "$windows"`
+        ;;
+esac
+
+## if it's not found, then search the path
+if [ -z "$prog" ]; then
+    argv0=`readlink -f "$0"`
+    IFS=:
+    for p in $PATH; do
+        rp=`readlink -f "$p/$posix"`
+        [ -x "$rp" ] && [ `stat -f%i "$argv0" 2>/dev/null || echo "$argv0"` != `stat -f%i "$rp" 2>/dev/null || echo "$rp"` ] && prog="$rp"
+    done
+fi
+
+# go for it...or not.
+[ -z "$prog" ] && echo "Unable to locate $posix" 1>&2 && exit 1
+"$prog" "$@"
+exit $?
