Changed the error message emitted by some of the scripts under posix/bin.

diff --git a/posix/bin/dig b/posix/bin/dig
--- a/posix/bin/dig
+++ b/posix/bin/dig
@@ -19,7 +19,7 @@ if [ -z "$prog" ]; then
     unset IFS
 fi
 
-[ -z "$prog" ] && echo "Unable to locate $posix" 1>&2 && exit 1
+[ -z "$prog" ] && echo "Unable to locate binary for program: $posix" 1>&2 && exit 1
 
 "$prog" "$@"
 exit $?
diff --git a/posix/bin/ocaml b/posix/bin/ocaml
--- a/posix/bin/ocaml
+++ b/posix/bin/ocaml
@@ -12,17 +12,6 @@ case "$platform" in
         posix=`basename "$posix"`
 esac
 
-## if we're on a posixy platform, then search the path
-if [ -z "$prog" ]; then
-    argv0=`readlink -f "$0"`
-    IFS=:
-    for p in $PATH; do
-        rp=`readlink -f "$p/$posix"`
-        [ -x "$rp" ] && [ `stat -f%i "$argv0" 2>/dev/null || echo "$argv0"` != `stat -f%i "$rp" 2>/dev/null || echo "$rp"` ] && prog="$rp"
-    done
-    unset IFS
-fi
-
 # setup the opam environment
 opam=`type -p "opam"`
 if [ -z "$opam" ]; then
@@ -31,8 +20,13 @@ else
     eval `$opam env`
 fi
 
+## if we're on a posixy platform, then search the path
+if [ -z "$prog" ]; then
+    prog=`type -P "$posix"`
+fi
+
 # go for it...or not.
-[ -z "$prog" ] && echo "Unable to locate $prog" 1>&2 && exit 1
+[ -z "$prog" ] && echo "Unable to locate binary for program: $posix" 1>&2 && exit 1
 
 eval "$prog" $args "$@"
 exit $?
diff --git a/posix/bin/tshark b/posix/bin/tshark
--- a/posix/bin/tshark
+++ b/posix/bin/tshark
@@ -10,8 +10,6 @@ case "${platform}" in
     msys|cygwin)
         prog=`[ -x "$windows" ] && echo "$windows"`
         ;;
-    *)
-        posix=`basename "$posix"`
 esac
 
 ## if we're on a posixy platform, then search the path
@@ -26,7 +24,7 @@ if [ -z "$prog" ]; then
 fi
 
 ## now try and run shit
-[ -z "$prog" ] && echo "Unable to locate $prog" 1>&2 && exit 1
+[ -z "$prog" ] && echo "Unable to locate binary for program: $posix" 1>&2 && exit 1
 
 eval "$prog" $args "$@"
 exit $?
diff --git a/posix/bin/vim b/posix/bin/vim
--- a/posix/bin/vim
+++ b/posix/bin/vim
@@ -25,7 +25,7 @@ if [ -z "$prog" ]; then
 fi
 
 # go for it...or not.
-[ -z "$prog" ] && echo "Unable to locate $prog" 1>&2 && exit 1
+[ -z "$prog" ] && echo "Unable to locate binary for program: $posix" 1>&2 && exit 1
 
 "$prog" "$@"
 exit $?
