Added path detection to some of the scripts under the posix/bin subdirectory.

diff --git a/posix/bin/tor b/posix/bin/tor
--- a/posix/bin/tor
+++ b/posix/bin/tor
@@ -1,2 +1,17 @@
 #!/bin/sh
-/usr/sbin/tor -f $HOME/.torrc
+posix=`type -P tor`
+
+argv0=`readlink -f "$0"`
+IFS=:
+for p in $PATH; do
+    rp=`readlink -f "$p/$posix"`
+    [ -x "$rp" ] && [ `stat -f%i "$argv0" 2>/dev/null || echo "$argv0"` != `stat -f%i "$rp" 2>/dev/null || echo "$rp"` ] && prog="$rp"
+done
+unset IFS
+
+if [ -z "$prog" ]; then
+    echo "Unable to locate binary for program: $posix" 1>&2
+    exit 1
+fi
+
+exec "$prog" --RunAsDaemon --PidFile $HOME/.tor.pid -f $HOME/.torrc
diff --git a/posix/bin/tor-refresh b/posix/bin/tor-refresh
--- a/posix/bin/tor-refresh
+++ b/posix/bin/tor-refresh
@@ -1,3 +1,11 @@
 #!/bin/sh
-echo "refreshing tor..."
-kill -HUP $(cat $HOME/.tor.pid)
+pidfile=$HOME/.tor.pid
+
+if [ -e "$pidfile" ]; then
+    echo "Refreshing tor using pid found at $pidfile..." 1>&2
+    cat "$HOME/.tor.pid" | xargs kill -HUP
+    exit 0
+else
+    echo "Unable to determine pid due to missing file: $pidfile" 1>&2
+    exit 1
+fi
diff --git a/posix/bin/torify b/posix/bin/torify
--- a/posix/bin/torify
+++ b/posix/bin/torify
@@ -1,6 +1,22 @@
 #!/bin/sh
-if $( test ! -e $HOME/.tor.pid ); then
-    tor -f $HOME/.torrc --RunAsDaemon 1 --PidFile $HOME/.tor.pid
+posix=`type -P tsocks`
+
+argv0=`readlink -f "$0"`
+IFS=:
+for p in $PATH; do
+    rp=`readlink -f "$p/$posix"`
+    [ -x "$rp" ] && [ `stat -f%i "$argv0" 2>/dev/null || echo "$argv0"` != `stat -f%i "$rp" 2>/dev/null || echo "$rp"` ] && prog="$rp"
+done
+unset IFS
+
+if [ -z "$prog" ]; then
+    echo "Unable to locate binary for program: $posix" 1>&2
+    exit 1
+fi
+
+if [ ! -e "$HOME/.tor.pid" ]; then
+    echo "Pidfile $HOME/.tor.pid not found!" 1>&2
+    exit 1
 fi
 
 if $( test -e $HOME/.tsocks.conf ); then
@@ -9,4 +25,4 @@ else
     TSOCKS_CONF_FILE=/etc/tor/tor-tsocks.conf
 fi
 export TSOCKS_CONF_FILE
-exec tsocks "$@"
+exec "$prog" "$@"
