Fixed a bug in posix/bin/vim when trying to locate the program in a posixy environment

diff --git a/posix/bin/vim b/posix/bin/vim
--- a/posix/bin/vim
+++ b/posix/bin/vim
@@ -9,6 +9,8 @@ case "$platform" in
     msys|cygwin)
         prog=`[ -x "$windows" ] && echo "$windows"`
         ;;
+    *)
+        posix=`basename "$posix"`
 esac
 
 ## if it's not found, then search the path
@@ -22,6 +24,6 @@ if [ -z "$prog" ]; then
 fi
 
 # go for it...or not.
-[ -z "$prog" ] && echo "Unable to locate $posix" 1>&2 && exit 1
+[ -z "$prog" ] && echo "Unable to locate $prog" 1>&2 && exit 1
 "$prog" "$@"
 exit $?
